version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=359538883686.dkr.ecr.us-east-1.amazonaws.com/docker-repo
  build:
    commands:
      - docker build -t test1:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":<TASK_DEFINITION_NAME>,"imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
